---
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  message = FALSE,
  warning = FALSE,
  fig.path = "figure/"
)

library(dplyr)
library(ggplot2)
library(here)
library(purrr)
library(R6)
library(tictoc)
library(tidyr)

source(here("R", "all_pairs.R"))
source(here("R", "grid_lines.R"))
source(here("R", "is_subset.R"))
source(here("R", "remove_both.R"))
source(here("R", "roomr62.R"))
```

# more-maximal-room-squares

<!-- badges: start -->
<!-- badges: end -->

```{r room}
n <- 10

r <- Room$new(size = n)

tic()
for(e in r$empty_cells) {
  for(p in r$free_pairs) {
    if(r$is_available(e, p)) {
      r$set(e, p)
      break()
    }
  }
}
toc()
```

```{r plot, echo=FALSE}
library(glue)
library(scales)

nf <- r$n_filled
v <- label_percent()(r$volume)

ggplot(data = r$cells %>% pivot_wider(), aes(col, row)) +
  geom_segment(data = grid_lines(n - 1, n - 1), aes(x = x, y = y, xend = xend, yend = yend), size = .1) +
  geom_text(data = r$cells %>% pivot_wider() %>% filter(!is.na(first)), aes(label = paste(first, second, sep = ","))) +
  scale_y_reverse() +
  coord_fixed() + 
  theme_void() +
  theme(
    legend.position  = "none"
  ) +
  labs(
    title = glue("A maximal partial Room square of order {n}"),
    subtitle = glue("Number of filled cells: {nf}, Volume: {v}.")
  )
```

# Results

```{r}
library(dplyr)
library(here)
library(readr)

results <- read_rds(here("data", "results.rds"))
meszka <- read_rds(here("data", "meszka-rosa-table.rds"))

final_results <- results %>%
  filter(n >= 50) %>%
  group_by(n) %>%
  summarise(t3 = max(n_filled)) %>%
  left_join(meszka) %>%
  mutate(
    `t3 - t1` = t3 - t1,
           r3 = t3/nc2
  ) %>%
  select(n, nc2, t1, t2, t3, r1, r2, r3)

print(final_results, n = Inf)
```
